apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: d03zvclqn-python 
  janus-idp.io/tekton: d03zvclqn-python
  backstage.io/kubernetes-id: d03zvclqn-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d03zvclqn-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  